@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "PYTHON_EXE="

echo Searching for Python available to the GitHub runner account...

rem 1) Commands already available in PATH.
for %%N in (python.exe python3.exe py.exe) do (
  if not defined PYTHON_EXE (
    for /f "delims=" %%P in ('where %%N 2^>nul') do (
      if not defined PYTHON_EXE call :try_python "%%~fP"
    )
  )
)

rem 2) Python Launcher can be installed outside PATH.
if not defined PYTHON_EXE call :try_python "%LocalAppData%\Programs\Python\Launcher\py.exe"
if not defined PYTHON_EXE call :try_python "%SystemRoot%\py.exe"
if not defined PYTHON_EXE call :try_python "%SystemRoot%\System32\py.exe"

rem 3) Registered Python executable paths for the current user and the computer.
if not defined PYTHON_EXE call :search_registry "HKCU\Software\Python\PythonCore"
if not defined PYTHON_EXE call :search_registry "HKLM\Software\Python\PythonCore"
if not defined PYTHON_EXE call :search_registry "HKLM\Software\WOW6432Node\Python\PythonCore"

rem 4) Common per-user Python installations.
if not defined PYTHON_EXE (
  for /d %%D in ("%LocalAppData%\Programs\Python\Python*") do (
    if not defined PYTHON_EXE call :try_python "%%~fD\python.exe"
  )
)
if not defined PYTHON_EXE call :try_python "%UserProfile%\anaconda3\python.exe"
if not defined PYTHON_EXE call :try_python "%UserProfile%\miniconda3\python.exe"
if not defined PYTHON_EXE call :try_python "%LocalAppData%\anaconda3\python.exe"
if not defined PYTHON_EXE call :try_python "%LocalAppData%\miniconda3\python.exe"
if not defined PYTHON_EXE call :try_python "%UserProfile%\scoop\apps\python\current\python.exe"

rem 5) Common computer-wide installations. Reading these folders does not require admin rights.
if not defined PYTHON_EXE (
  for /d %%D in ("%ProgramFiles%\Python*") do (
    if not defined PYTHON_EXE call :try_python "%%~fD\python.exe"
  )
)
if defined ProgramFiles(x86) if not defined PYTHON_EXE (
  for /d %%D in ("%ProgramFiles(x86)%\Python*") do (
    if not defined PYTHON_EXE call :try_python "%%~fD\python.exe"
  )
)
if not defined PYTHON_EXE call :try_python "%ProgramData%\Anaconda3\python.exe"
if not defined PYTHON_EXE call :try_python "%ProgramData%\Miniconda3\python.exe"
if not defined PYTHON_EXE (
  for /d %%D in ("C:\Python*") do (
    if not defined PYTHON_EXE call :try_python "%%~fD\python.exe"
  )
)

rem 6) WinGet packages can live in a versioned folder not covered above.
if not defined PYTHON_EXE if exist "%LocalAppData%\Microsoft\WinGet\Packages" (
  for /r "%LocalAppData%\Microsoft\WinGet\Packages" %%F in (python.exe) do (
    if not defined PYTHON_EXE call :try_python "%%~fF"
  )
)

rem 7) Last targeted search inside the user's local Programs folder.
if not defined PYTHON_EXE if exist "%LocalAppData%\Programs" (
  for /r "%LocalAppData%\Programs" %%F in (python.exe) do (
    if not defined PYTHON_EXE call :try_python "%%~fF"
  )
)

if not defined PYTHON_EXE (
  echo ERROR: No usable Python installation is visible to the Windows account running this GitHub runner.
  echo Checked PATH, Python Launcher, registry, standard Python, Conda, Scoop and WinGet locations.
  echo This message is generated by scripts\prepare-python.cmd; it is not a Windows or IT system response.
  exit /b 1
)

echo Found Python: !PYTHON_EXE!
"!PYTHON_EXE!" -c "import sys; print(sys.version); raise SystemExit(0 if sys.version_info >= (3, 11) else 1)"
if errorlevel 1 (
  echo ERROR: Python 3.11 or newer is required.
  exit /b 1
)

rem Create an isolated environment inside the checked-out repository.
rem This avoids PATH changes and does not install packages system-wide.
if exist ".venv\Scripts\python.exe" rmdir /s /q ".venv"
"!PYTHON_EXE!" -m venv .venv
if errorlevel 1 (
  echo ERROR: Python was found, but it could not create the local .venv environment.
  exit /b 1
)

".venv\Scripts\python.exe" --version
".venv\Scripts\python.exe" -m pip --version
if errorlevel 1 (
  echo ERROR: pip is unavailable in the local Python environment.
  exit /b 1
)

endlocal
exit /b 0

:try_python
if defined PYTHON_EXE exit /b 0
set "CANDIDATE=%~1"
if not defined CANDIDATE exit /b 0
if not exist "%CANDIDATE%" exit /b 0
"%CANDIDATE%" -c "import sys; raise SystemExit(0 if sys.version_info.major == 3 else 1)" >nul 2>nul
if errorlevel 1 exit /b 0
set "PYTHON_EXE=%CANDIDATE%"
exit /b 0

:search_registry
set "REGROOT=%~1"
for /f "tokens=1,2,*" %%A in ('reg query "%REGROOT%" /s /v ExecutablePath 2^>nul ^| findstr /i "ExecutablePath"') do (
  if not defined PYTHON_EXE if /i "%%A"=="ExecutablePath" call :try_python "%%C"
)
for /f "tokens=1,2,*" %%A in ('reg query "%REGROOT%" /s /ve 2^>nul ^| findstr /i "REG_SZ"') do (
  if not defined PYTHON_EXE if /i "%%B"=="REG_SZ" call :try_python "%%C\python.exe"
)
exit /b 0
